// Generated by morphir-elm

import * as codecs from "./../../../../morphir/internal/Codecs";

export namespace Morphir_Reference_Model_Issues_Common {
  export type FloatAlias = number;

  export function decodeFloatAlias(input: any): FloatAlias {
    return codecs.decodeFloat(input);
  }

  export function encodeFloatAlias(value: FloatAlias): any {
    return codecs.encodeFloat(value);
  }
}
