// Generated by morphir-elm

import * as codecs from "./../../../../morphir/internal/Codecs"

export namespace Morphir_Reference_Model_Issues_Common {
  
  export type FloatAlias = number
  
  export function decodeFloatAlias(varDecoders, input) {
  return codecs.decodeFloat(input);
  }
  
  export function encodeFloatAlias(varEncoders, value) {
  return codecs.encodeFloat(value);
  }
  
}

