// Generated by morphir-elm

import * as codecs from "./../../../../morphir/internal/Codecs"

export namespace Morphir_Reference_Model_Issues_Issue407 {
  
  export type BigRecord = {
    field1: number;
    field2: number;
    field3: number;
    field4: number;
    field5: number;
    field6: number;
    field7: number;
    field8: number;
    field9: number;
    field10: number;
    field11: number;
    field12: number;
    field13: number;
    field14: number;
    field15: number;
    field16: number;
    field17: number;
    field18: number;
    field19: number;
    field20: number;
    field21: number;
    field22: number;
    field23: number;
  }
  
  export function decodeBigRecord(varDecoders, input) {
  return codecs.decodeRecord(new Map([["field1", codecs.decodeInt.bind(null)], ["field2", codecs.decodeInt.bind(null)], ["field3", codecs.decodeInt.bind(null)], ["field4", codecs.decodeInt.bind(null)], ["field5", codecs.decodeInt.bind(null)], ["field6", codecs.decodeInt.bind(null)], ["field7", codecs.decodeInt.bind(null)], ["field8", codecs.decodeInt.bind(null)], ["field9", codecs.decodeInt.bind(null)], ["field10", codecs.decodeInt.bind(null)], ["field11", codecs.decodeInt.bind(null)], ["field12", codecs.decodeInt.bind(null)], ["field13", codecs.decodeInt.bind(null)], ["field14", codecs.decodeInt.bind(null)], ["field15", codecs.decodeInt.bind(null)], ["field16", codecs.decodeInt.bind(null)], ["field17", codecs.decodeInt.bind(null)], ["field18", codecs.decodeInt.bind(null)], ["field19", codecs.decodeInt.bind(null)], ["field20", codecs.decodeInt.bind(null)], ["field21", codecs.decodeInt.bind(null)], ["field22", codecs.decodeInt.bind(null)], ["field23", codecs.decodeInt.bind(null)]]), input);
  }
  
  export function encodeBigRecord(varEncoders, value) {
  return codecs.encodeRecord(new Map([["field1", codecs.encodeInt.bind(null)], ["field2", codecs.encodeInt.bind(null)], ["field3", codecs.encodeInt.bind(null)], ["field4", codecs.encodeInt.bind(null)], ["field5", codecs.encodeInt.bind(null)], ["field6", codecs.encodeInt.bind(null)], ["field7", codecs.encodeInt.bind(null)], ["field8", codecs.encodeInt.bind(null)], ["field9", codecs.encodeInt.bind(null)], ["field10", codecs.encodeInt.bind(null)], ["field11", codecs.encodeInt.bind(null)], ["field12", codecs.encodeInt.bind(null)], ["field13", codecs.encodeInt.bind(null)], ["field14", codecs.encodeInt.bind(null)], ["field15", codecs.encodeInt.bind(null)], ["field16", codecs.encodeInt.bind(null)], ["field17", codecs.encodeInt.bind(null)], ["field18", codecs.encodeInt.bind(null)], ["field19", codecs.encodeInt.bind(null)], ["field20", codecs.encodeInt.bind(null)], ["field21", codecs.encodeInt.bind(null)], ["field22", codecs.encodeInt.bind(null)], ["field23", codecs.encodeInt.bind(null)]]), value);
  }
  
}

