// Generated by morphir-elm



export namespace Morphir_Reference_Model_Issues_Issue407 {
  
  export type BigRecord = {
    Field1: number;
    Field2: number;
    Field3: number;
    Field4: number;
    Field5: number;
    Field6: number;
    Field7: number;
    Field8: number;
    Field9: number;
    Field10: number;
    Field11: number;
    Field12: number;
    Field13: number;
    Field14: number;
    Field15: number;
    Field16: number;
    Field17: number;
    Field18: number;
    Field19: number;
    Field20: number;
    Field21: number;
    Field22: number;
    Field23: number;
  }
  
}

