// Generated by morphir-elm

import * as codecs from "./../../../../morphir/internal/Codecs";

export namespace Morphir_Reference_Model_Issues_Issue401 {
  export type Foo = {
    field: string;
  };

  export function decodeFoo(input: any): Foo {
    return codecs.decodeRecord(
      codecs.buildCodecMap([["field", codecs.decodeString]]),
      input
    );
  }

  export function encodeFoo(value: Foo): any {
    return codecs.encodeRecord(
      codecs.buildCodecMap([["field", codecs.encodeString]]),
      value
    );
  }
}
