// Generated by morphir-elm

import * as codecs from "./../../../../morphir/internal/Codecs";

export namespace Morphir_Reference_Model_Issues_Issue330 {
  export class MyType {
    kind: "MyType" = "MyType";

    constructor(public arg1: string) {}
  }

  export function decodeMyType(input: any): MyType {
    codecs.preprocessCustomTypeVariant("MyType", 1, input);
    return new MyType(codecs.decodeString(input[1]));
  }

  export function encodeMyType(value: MyType): any {
    return [value.kind, codecs.encodeString(value.arg1)];
  }
}
