// Generated by morphir-elm

import * as codecs from "./../../../../morphir/internal/Codecs";

export namespace Morphir_Reference_Model_Issues_Issue432 {
  export class Custom {
    kind: "Custom" = "Custom";

    constructor() {}
  }

  export function decodeCustom(input: any): Custom {
    codecs.preprocessCustomTypeVariant("Custom", 0, input);
    return new Custom();
  }

  export function encodeCustom(value: Custom): any {
    return value.kind;
  }
}
