// Generated by morphir-elm

import * as codecs from "./../../../../morphir/internal/Codecs";

export namespace Morphir_Reference_Model_Issues_Issue273 {
  type MyRecord = {
    foo: string;
  };

  function decodeMyRecord(input: any): MyRecord {
    return codecs.decodeRecord(
      codecs.buildCodecMap([["foo", codecs.decodeString]]),
      input
    );
  }

  function encodeMyRecord(value: MyRecord): any {
    return codecs.encodeRecord(
      codecs.buildCodecMap([["foo", codecs.encodeString]]),
      value
    );
  }
}
