// Generated by morphir-elm

import * as codecs from "./../../../../morphir/internal/Codecs"

export namespace Morphir_Reference_Model_Issues_Issue401 {
  
  export type Foo = {
    field: string;
  }
  
  export function decodeFoo(varDecoders, input) {
  return codecs.decodeRecord(new Map([["field", codecs.decodeString.bind(null)]]), input);
  }
  
  export function encodeFoo(varEncoders, value) {
  return codecs.encodeRecord(new Map([["field", codecs.encodeString.bind(null)]]), value);
  }
  
}

