// Generated by morphir-elm

import * as codecs from "./../../../../morphir/internal/Codecs";

export namespace Morphir_Reference_Model_Issues_Issue364 {
  export type Input = {
    key1: string;
    key2: string;
    value: number;
  };

  export function decodeInput(input: any): Input {
    return codecs.decodeRecord(
      codecs.buildCodecMap([
        ["key1", codecs.decodeString],
        ["key2", codecs.decodeString],
        ["value", codecs.decodeFloat],
      ]),
      input
    );
  }

  export function encodeInput(value: Input): any {
    return codecs.encodeRecord(
      codecs.buildCodecMap([
        ["key1", codecs.encodeString],
        ["key2", codecs.encodeString],
        ["value", codecs.encodeFloat],
      ]),
      value
    );
  }
}
