// Generated by morphir-elm

import { Morphir_Reference_Model_Issues_PatternModel_BasicEnum } from "./../../../../morphir/reference/model/issues/patternmodel/BasicEnum"
import { Morphir_Reference_Model_Issues_PatternModel_OtherBasicEnum } from "./../../../../morphir/reference/model/issues/patternmodel/OtherBasicEnum"

export namespace Morphir_Reference_Model_Issues_Issue409 {
  
  export type BasicRule = {
    basicEnum: Morphir_Reference_Model_Issues_PatternModel_BasicEnum.BasicEnum;
    otherBasicEnum: Morphir_Reference_Model_Issues_PatternModel_OtherBasicEnum.OtherBasicEnum;
    id: string;
  }
  
}

