// Generated by morphir-elm

import * as codecs from "./../../../../morphir/internal/Codecs"

export namespace Morphir_Reference_Model_Issues_Issue364 {
  
  export type Input = {
    key1: string;
    key2: string;
    value: number;
  }
  
  export function decodeInput(varDecoders, input) {
  return codecs.decodeRecord(new Map([["key1", codecs.decodeString.bind(null)], ["key2", codecs.decodeString.bind(null)], ["value", codecs.decodeFloat.bind(null)]]), input);
  }
  
  export function encodeInput(varEncoders, value) {
  return codecs.encodeRecord(new Map([["key1", codecs.encodeString.bind(null)], ["key2", codecs.encodeString.bind(null)], ["value", codecs.encodeFloat.bind(null)]]), value);
  }
  
}

