// Generated by morphir-elm

import * as codecs from "./../../../../morphir/internal/Codecs"

export namespace Morphir_Reference_Model_Issues_Issue330 {
  export interface MyType {
    kind: "MyType";
    arg1: string;
  }
  
  export function decodeMyType(varDecoders, input) {
  return codecs.decodeCustomTypeVariant("MyType", ["Arg1"], [codecs.decodeString.bind(null)], input);
  }
  
}

