// Generated by morphir-elm

import { Morphir_Reference_Model_Issues_PatternModel_BasicEnum } from "./../../../../morphir/reference/model/issues/patternmodel/BasicEnum"
import { Morphir_Reference_Model_Issues_PatternModel_OtherBasicEnum } from "./../../../../morphir/reference/model/issues/patternmodel/OtherBasicEnum"

export namespace Morphir_Reference_Model_Issues_Issue409 {
  
  export type BasicRule = {
    BasicEnum: Morphir_Reference_Model_Issues_PatternModel_BasicEnum.BasicEnum;
    OtherBasicEnum: Morphir_Reference_Model_Issues_PatternModel_OtherBasicEnum.OtherBasicEnum;
    Id: string;
  }
  
}

