// Generated by morphir-elm

import * as codecs from "./../../../../morphir/internal/Codecs"

export namespace Morphir_Reference_Model_Issues_Issue432 {
  export interface Custom {
    kind: "Custom";
  }
  
}

