// Generated by morphir-elm

import * as codecs from "./../../../../morphir/internal/Codecs"

export namespace Morphir_Reference_Model_Issues_Issue273 {
  
  type MyRecord = {
    foo: string;
  }
  
  function decodeMyRecord(varDecoders, input) {
  return codecs.decodeRecord(new Map([["foo", codecs.decodeString.bind(null)]]), input);
  }
  
  function encodeMyRecord(varEncoders, value) {
  return codecs.encodeRecord(new Map([["foo", codecs.encodeString.bind(null)]]), value);
  }
  
}

