// Generated by morphir-elm

import * as codecs from "./../../../../morphir/internal/Codecs"

export namespace Morphir_Reference_Model_Issues_Issue349 {
  
  export type Result<a> = {
    foo: Array<a>;
  }
  
  export function decodeResult(varDecoders, input) {
  return codecs.decodeRecord(new Map([["foo", codecs.decodeList.bind(null, varDecoders.A.bind(null))]]), input);
  }
  
  export function encodeResult(varEncoders, value) {
  return codecs.encodeRecord(new Map([["foo", codecs.encodeList.bind(null, varEncoders.a.bind(null))]]), value);
  }
  
}

