// Generated by morphir-elm



export namespace Morphir_Reference_Model_Issues_PatternModel_BasicEnum {
  
  export type BasicEnum = Five | Four | None | One | Six | Three | Two
  
  export interface Five {
    kind: "Five";
  }
  
  export interface Four {
    kind: "Four";
  }
  
  export interface None {
    kind: "None";
  }
  
  export interface One {
    kind: "One";
  }
  
  export interface Six {
    kind: "Six";
  }
  
  export interface Three {
    kind: "Three";
  }
  
  export interface Two {
    kind: "Two";
  }
  
}

