// Generated by morphir-elm



export namespace Morphir_Reference_Model_Issues_PatternModel_OtherBasicEnum {
  
  export type OtherBasicEnum = A | B | C | D | E | F | None
  
  export interface A {
    kind: "A";
  }
  
  export interface B {
    kind: "B";
  }
  
  export interface C {
    kind: "C";
  }
  
  export interface D {
    kind: "D";
  }
  
  export interface E {
    kind: "E";
  }
  
  export interface F {
    kind: "F";
  }
  
  export interface None {
    kind: "None";
  }
  
}

