// Generated by morphir-elm



export namespace Codethink_PrizeDraws_AutoGen {
  export interface Car {
    kind: "Car";
    arg1: number;
    arg2: string;
    arg3: string;
  }
  
  
  export type Cash = number
  
  
  export type GemStone = Diamond | Emerald | Opal | Ruby | Saphire | Topaz
  
  export interface Diamond {
    kind: "Diamond";
  }
  
  export interface Emerald {
    kind: "Emerald";
  }
  
  export interface Opal {
    kind: "Opal";
  }
  
  export interface Ruby {
    kind: "Ruby";
  }
  
  export interface Saphire {
    kind: "Saphire";
  }
  
  export interface Topaz {
    kind: "Topaz";
  }
  
  
  export type Holiday = {
    location: string;
    duration: number;
    allExpenses: boolean;
  }
  
  
  export type Prize<mainPrizeType, awardType> = Award<mainPrizeType, awardType> | MainPrize<mainPrizeType, awardType>
  
  export interface Award<mainPrizeType, awardType> {
    kind: "Award";
    arg1: string;
    arg2: awardType;
  }
  
  export interface MainPrize<mainPrizeType, awardType> {
    kind: "MainPrize";
    arg1: mainPrizeType;
  }
  
}

