// Generated by morphir-elm

import { Morphir_IR_Package } from "./../../morphir/ir/Package"
import { Morphir_IR_Type } from "./../../morphir/ir/Type"

export namespace Morphir_IR_Distribution {
  /* Type that represents a package distribution. Currently the only distribution type we provide is a `Library`.
  */
  export type Distribution = Library
  
  export interface Library {
    kind: "Library";
    arg1: Morphir_IR_Package.PackageName;
    arg2: Array<[Morphir_IR_Package.PackageName, Morphir_IR_Package.Specification<[]>]>;
    arg3: Morphir_IR_Package.Definition<[], Morphir_IR_Type.Type<[]>>;
  }
  
}

