// Generated by morphir-elm

import { Morphir_IR_Name } from "./../../morphir/ir/Name"
import { Morphir_IR_Path } from "./../../morphir/ir/Path"

export namespace Morphir_IR_FQName {
  /* Type that represents a fully-qualified name.
  The parameters are PackagePath ModulePath Name
  */
  export type FQName = [Morphir_IR_Path.Path, Morphir_IR_Path.Path, Morphir_IR_Name.Name]
  
}

