// Generated by morphir-elm

import * as codecs from "./../../morphir/internal/Codecs";
import { Morphir_IR_Name } from "./../../morphir/ir/Name";
import { Morphir_IR_Path } from "./../../morphir/ir/Path";

export namespace Morphir_IR_FQName {
  /* Type that represents a fully-qualified name.
  The parameters are PackagePath ModulePath Name
  */
  export type FQName = [
    Morphir_IR_Path.Path,
    Morphir_IR_Path.Path,
    Morphir_IR_Name.Name
  ];

  export function decodeFQName(input: any): FQName {
    return codecs.decodeTuple(
      [
        Morphir_IR_Path.decodePath,
        Morphir_IR_Path.decodePath,
        Morphir_IR_Name.decodeName,
      ],
      input
    );
  }

  export function encodeFQName(value: FQName): any {
    return codecs.encodeTuple(
      [
        Morphir_IR_Path.encodePath,
        Morphir_IR_Path.encodePath,
        Morphir_IR_Name.encodeName,
      ],
      value
    );
  }
}
