// Generated by morphir-elm

import * as codecs from "./../../morphir/internal/Codecs"
import { Morphir_IR_Name } from "./../../morphir/ir/Name"
import { Morphir_IR_Path } from "./../../morphir/ir/Path"

export namespace Morphir_IR_FQName {
  /* Type that represents a fully-qualified name.
  The parameters are PackagePath ModulePath Name
  */
  export type FQName = [Morphir_IR_Path.Path, Morphir_IR_Path.Path, Morphir_IR_Name.Name]
  
  export function decodeFQName(varDecoders, input) {
  return codecs.decodeTuple([Morphir_IR_Path.decodePath.bind(null, varDecoders), Morphir_IR_Path.decodePath.bind(null, varDecoders), Morphir_IR_Name.decodeName.bind(null, varDecoders)], input);
  }
  
  export function encodeFQName(varEncoders, value) {
  return codecs.encodeTuple([codecs.encodeUnit.bind(null), codecs.encodeUnit.bind(null), codecs.encodeUnit.bind(null)], value);
  }
  
}

