// Generated by morphir-elm

import * as codecs from "./../../morphir/internal/Codecs";

export namespace Morphir_IR_Name {
  /* Type that represents a name that is made up of words.
   */
  export type Name = Array<string>;

  export function decodeName(input: any): Name {
    return codecs.decodeList(codecs.decodeString, input);
  }

  export function encodeName(value: Name): any {
    return codecs.encodeList(codecs.encodeString, value);
  }
}
