// Generated by morphir-elm

import * as codecs from "./../../morphir/internal/Codecs"

export namespace Morphir_IR_Name {
  /* Type that represents a name that is made up of words.
  */
  export type Name = Array<string>
  
  export function decodeName(varDecoders, input) {
  return codecs.decodeList(codecs.decodeString.bind(null), input);
  }
  
  export function encodeName(varEncoders, value) {
  return codecs.encodeList(codecs.encodeString.bind(null), value);
  }
  
}

