// Generated by morphir-elm

import { Morphir_IR_AccessControlled } from "./../../morphir/ir/AccessControlled"
import { Morphir_IR_Module } from "./../../morphir/ir/Module"
import { Morphir_IR_Path } from "./../../morphir/ir/Path"

export namespace Morphir_IR_Package {
  /* Type that represents a package definition. A package definition contains all the details including implementation
  and private types and values. The modules field is a dictionary keyed by module name that contains access controlled
  module definitions. The `AccessControlled` adds access classifiers to each module to differentiate public and private
  modules.
  */
  export type Definition<ta, va> = {
    Modules: Array<[Morphir_IR_Module.ModuleName, Morphir_IR_AccessControlled.AccessControlled<Morphir_IR_Module.Definition<ta, va>>]>;
  }
  
  /* A package name is a globally unique identifier for a package. It is represented by a path, which is a list of names.
  */
  export type PackageName = Morphir_IR_Path.Path
  
  /* Type that represents a package specification. A package specification only contains types that are exposed publicly
  and type signatures for values that are exposed publicly.
  */
  export type Specification<ta> = {
    Modules: Array<[Morphir_IR_Module.ModuleName, Morphir_IR_Module.Specification<ta>]>;
  }
  
}

