// Generated by morphir-elm

import * as codecs from "./../../morphir/internal/Codecs"
import { Morphir_IR_Name } from "./../../morphir/ir/Name"

export namespace Morphir_IR_Path {
  /* Type that represents a path as a list of names.
  */
  export type Path = Array<Morphir_IR_Name.Name>
  
  export function decodePath(varDecoders, input) {
  return codecs.decodeList(codecs.decodeUnit.bind(null), input);
  }
  
  export function encodePath(varEncoders, value) {
  return codecs.encodeList(codecs.encodeUnit.bind(null), value);
  }
  
}

