// Generated by morphir-elm

import * as codecs from "./../../morphir/internal/Codecs"
import { Morphir_IR_Name } from "./../../morphir/ir/Name"
import { Morphir_IR_Path } from "./../../morphir/ir/Path"

export namespace Morphir_IR_QName {
  export interface QName {
    kind: "QName";
    arg1: Morphir_IR_Path.Path;
    arg2: Morphir_IR_Name.Name;
  }
  
}

