// Generated by morphir-elm

import * as codecs from "./../../morphir/internal/Codecs"
import { Morphir_IR_Name } from "./../../morphir/ir/Name"
import { Morphir_IR_Path } from "./../../morphir/ir/Path"

export namespace Morphir_IR_QName {
  export interface QName {
    kind: "QName";
    arg1: Morphir_IR_Path.Path;
    arg2: Morphir_IR_Name.Name;
  }
  
  export function decodeQName(varDecoders, input) {
  return codecs.decodeCustomTypeVariant("QName", ["Arg1", "Arg2"], [Morphir_IR_Path.decodePath.bind(null, varDecoders), Morphir_IR_Name.decodeName.bind(null, varDecoders)], input);
  }
  
}

