// Generated by morphir-elm

import * as codecs from "./../../morphir/internal/Codecs";
import { Morphir_IR_Name } from "./../../morphir/ir/Name";
import { Morphir_IR_Path } from "./../../morphir/ir/Path";

export namespace Morphir_IR_QName {
  export class QName {
    kind: "QName" = "QName";

    constructor(
      public arg1: Morphir_IR_Path.Path,
      public arg2: Morphir_IR_Name.Name
    ) {}
  }

  export function decodeQName(input: any): QName {
    codecs.preprocessCustomTypeVariant("QName", 2, input);
    return new QName(
      Morphir_IR_Path.decodePath(input[1]),
      Morphir_IR_Name.decodeName(input[2])
    );
  }

  export function encodeQName(value: QName): any {
    return [
      value.kind,
      Morphir_IR_Path.encodePath(value.arg1),
      Morphir_IR_Name.encodeName(value.arg2),
    ];
  }
}
