// Generated by morphir-elm

import * as codecs from "./../../../morphir/internal/Codecs"

export namespace Morphir_Reference_Model_BooksAndRecords {
  
  export type Deal = {
    product: Morphir_Reference_Model_BooksAndRecords.ProductID;
    price: Morphir_Reference_Model_BooksAndRecords.Price;
    quantity: Morphir_Reference_Model_BooksAndRecords.Quantity;
  }
  
  export function decodeDeal(varDecoders, input) {
  return codecs.decodeRecord(new Map([["product", Morphir_Reference_Model_BooksAndRecords.decodeProductID.bind(null, varDecoders)], ["price", Morphir_Reference_Model_BooksAndRecords.decodePrice.bind(null, varDecoders)], ["quantity", Morphir_Reference_Model_BooksAndRecords.decodeQuantity.bind(null, varDecoders)]]), input);
  }
  
  export function encodeDeal(varEncoders, value) {
  return codecs.encodeRecord(new Map([["product", codecs.encodeUnit.bind(null)], ["price", codecs.encodeUnit.bind(null)], ["quantity", codecs.encodeUnit.bind(null)]]), value);
  }
  
  
  export type DealCmd = CloseDeal | OpenDeal
  
  export function decodeDealCmd(varDecoders, input) {
  let decoderMap = new Map();
  decoderMap.set("CloseDeal", decodeCloseDeal.bind(varDecoders));
  decoderMap.set("OpenDeal", decodeOpenDeal.bind(varDecoders));
  codecs.decodeCustomType(decoderMap, input);
  }
  
  
  
  export interface CloseDeal {
    kind: "CloseDeal";
    arg1: Morphir_Reference_Model_BooksAndRecords.ProductID;
  }
  
  export function decodeCloseDeal(varDecoders, input) {
  return codecs.decodeCustomTypeVariant("CloseDeal", ["Arg1"], [Morphir_Reference_Model_BooksAndRecords.decodeProductID.bind(null, varDecoders)], input);
  }
  
  export interface OpenDeal {
    kind: "OpenDeal";
    arg1: Morphir_Reference_Model_BooksAndRecords.ProductID;
    arg2: Morphir_Reference_Model_BooksAndRecords.Price;
    arg3: Morphir_Reference_Model_BooksAndRecords.Quantity;
  }
  
  export function decodeOpenDeal(varDecoders, input) {
  return codecs.decodeCustomTypeVariant("OpenDeal", ["Arg1", "Arg2", "Arg3"], [Morphir_Reference_Model_BooksAndRecords.decodeProductID.bind(null, varDecoders), Morphir_Reference_Model_BooksAndRecords.decodePrice.bind(null, varDecoders), Morphir_Reference_Model_BooksAndRecords.decodeQuantity.bind(null, varDecoders)], input);
  }
  
  
  export type DealEvent = DealClosed | DealNotFound | DealOpened | DuplicateDeal | InvalidPrice | InvalidQuantity
  
  export function decodeDealEvent(varDecoders, input) {
  let decoderMap = new Map();
  decoderMap.set("DealClosed", decodeDealClosed.bind(varDecoders));
  decoderMap.set("DealNotFound", decodeDealNotFound.bind(varDecoders));
  decoderMap.set("DealOpened", decodeDealOpened.bind(varDecoders));
  decoderMap.set("DuplicateDeal", decodeDuplicateDeal.bind(varDecoders));
  decoderMap.set("InvalidPrice", decodeInvalidPrice.bind(varDecoders));
  decoderMap.set("InvalidQuantity", decodeInvalidQuantity.bind(varDecoders));
  codecs.decodeCustomType(decoderMap, input);
  }
  
  
  
  export interface DealClosed {
    kind: "DealClosed";
    arg1: Morphir_Reference_Model_BooksAndRecords.ProductID;
  }
  
  export function decodeDealClosed(varDecoders, input) {
  return codecs.decodeCustomTypeVariant("DealClosed", ["Arg1"], [Morphir_Reference_Model_BooksAndRecords.decodeProductID.bind(null, varDecoders)], input);
  }
  
  export interface DealNotFound {
    kind: "DealNotFound";
    arg1: Morphir_Reference_Model_BooksAndRecords.ProductID;
  }
  
  export function decodeDealNotFound(varDecoders, input) {
  return codecs.decodeCustomTypeVariant("DealNotFound", ["Arg1"], [Morphir_Reference_Model_BooksAndRecords.decodeProductID.bind(null, varDecoders)], input);
  }
  
  export interface DealOpened {
    kind: "DealOpened";
    arg1: Morphir_Reference_Model_BooksAndRecords.ProductID;
    arg2: Morphir_Reference_Model_BooksAndRecords.Price;
    arg3: Morphir_Reference_Model_BooksAndRecords.Quantity;
  }
  
  export function decodeDealOpened(varDecoders, input) {
  return codecs.decodeCustomTypeVariant("DealOpened", ["Arg1", "Arg2", "Arg3"], [Morphir_Reference_Model_BooksAndRecords.decodeProductID.bind(null, varDecoders), Morphir_Reference_Model_BooksAndRecords.decodePrice.bind(null, varDecoders), Morphir_Reference_Model_BooksAndRecords.decodeQuantity.bind(null, varDecoders)], input);
  }
  
  export interface DuplicateDeal {
    kind: "DuplicateDeal";
    arg1: Morphir_Reference_Model_BooksAndRecords.ProductID;
  }
  
  export function decodeDuplicateDeal(varDecoders, input) {
  return codecs.decodeCustomTypeVariant("DuplicateDeal", ["Arg1"], [Morphir_Reference_Model_BooksAndRecords.decodeProductID.bind(null, varDecoders)], input);
  }
  
  export interface InvalidPrice {
    kind: "InvalidPrice";
    arg1: Morphir_Reference_Model_BooksAndRecords.Price;
  }
  
  export function decodeInvalidPrice(varDecoders, input) {
  return codecs.decodeCustomTypeVariant("InvalidPrice", ["Arg1"], [Morphir_Reference_Model_BooksAndRecords.decodePrice.bind(null, varDecoders)], input);
  }
  
  export interface InvalidQuantity {
    kind: "InvalidQuantity";
    arg1: Morphir_Reference_Model_BooksAndRecords.Quantity;
  }
  
  export function decodeInvalidQuantity(varDecoders, input) {
  return codecs.decodeCustomTypeVariant("InvalidQuantity", ["Arg1"], [Morphir_Reference_Model_BooksAndRecords.decodeQuantity.bind(null, varDecoders)], input);
  }
  
  
  export type ID = string
  
  export function decodeID(varDecoders, input) {
  return codecs.decodeString(input);
  }
  
  export function encodeID(varEncoders, value) {
  return codecs.encodeString(value);
  }
  
  
  export type Inventory = {
    supplier: Morphir_Reference_Model_BooksAndRecords.SupplierID;
    product: Morphir_Reference_Model_BooksAndRecords.ProductID;
    quantity: Morphir_Reference_Model_BooksAndRecords.Quantity;
  }
  
  export function decodeInventory(varDecoders, input) {
  return codecs.decodeRecord(new Map([["supplier", Morphir_Reference_Model_BooksAndRecords.decodeSupplierID.bind(null, varDecoders)], ["product", Morphir_Reference_Model_BooksAndRecords.decodeProductID.bind(null, varDecoders)], ["quantity", Morphir_Reference_Model_BooksAndRecords.decodeQuantity.bind(null, varDecoders)]]), input);
  }
  
  export function encodeInventory(varEncoders, value) {
  return codecs.encodeRecord(new Map([["supplier", codecs.encodeUnit.bind(null)], ["product", codecs.encodeUnit.bind(null)], ["quantity", codecs.encodeUnit.bind(null)]]), value);
  }
  
  
  export type Position = {
    product: Morphir_Reference_Model_BooksAndRecords.ProductID;
    quantity: Morphir_Reference_Model_BooksAndRecords.Quantity;
  }
  
  export function decodePosition(varDecoders, input) {
  return codecs.decodeRecord(new Map([["product", Morphir_Reference_Model_BooksAndRecords.decodeProductID.bind(null, varDecoders)], ["quantity", Morphir_Reference_Model_BooksAndRecords.decodeQuantity.bind(null, varDecoders)]]), input);
  }
  
  export function encodePosition(varEncoders, value) {
  return codecs.encodeRecord(new Map([["product", codecs.encodeUnit.bind(null)], ["quantity", codecs.encodeUnit.bind(null)]]), value);
  }
  
  
  export type Price = number
  
  export function decodePrice(varDecoders, input) {
  return codecs.decodeFloat(input);
  }
  
  export function encodePrice(varEncoders, value) {
  return codecs.encodeFloat(value);
  }
  
  
  export type ProductID = string
  
  export function decodeProductID(varDecoders, input) {
  return codecs.decodeString(input);
  }
  
  export function encodeProductID(varEncoders, value) {
  return codecs.encodeString(value);
  }
  
  
  export type Quantity = number
  
  export function decodeQuantity(varDecoders, input) {
  return codecs.decodeInt(input);
  }
  
  export function encodeQuantity(varEncoders, value) {
  return codecs.encodeInt(value);
  }
  
  
  export type SupplierID = string
  
  export function decodeSupplierID(varDecoders, input) {
  return codecs.decodeString(input);
  }
  
  export function encodeSupplierID(varEncoders, value) {
  return codecs.encodeString(value);
  }
  
}

