// Generated by morphir-elm

import * as codecs from "./../../../morphir/internal/Codecs"

export namespace Morphir_Reference_Model_Types {
  
  export type Custom = CustomNoArg | CustomOneArg | CustomTwoArg
  
  export function decodeCustom(varDecoders, input) {
  let decoderMap = new Map();
  decoderMap.set("CustomNoArg", decodeCustomNoArg.bind(varDecoders));
  decoderMap.set("CustomOneArg", decodeCustomOneArg.bind(varDecoders));
  decoderMap.set("CustomTwoArg", decodeCustomTwoArg.bind(varDecoders));
  codecs.decodeCustomType(decoderMap, input);
  }
  
  
  
  export interface CustomNoArg {
    kind: "CustomNoArg";
  }
  
  export function decodeCustomNoArg(varDecoders, input) {
  return codecs.decodeCustomTypeVariant("CustomNoArg", [], [], input);
  }
  
  export interface CustomOneArg {
    kind: "CustomOneArg";
    arg1: boolean;
  }
  
  export function decodeCustomOneArg(varDecoders, input) {
  return codecs.decodeCustomTypeVariant("CustomOneArg", ["Arg1"], [codecs.decodeBoolean.bind(null)], input);
  }
  
  export interface CustomTwoArg {
    kind: "CustomTwoArg";
    arg1: string;
    arg2: Morphir_Reference_Model_Types.Quantity;
  }
  
  export function decodeCustomTwoArg(varDecoders, input) {
  return codecs.decodeCustomTypeVariant("CustomTwoArg", ["Arg1", "Arg2"], [codecs.decodeString.bind(null), Morphir_Reference_Model_Types.decodeQuantity.bind(null, varDecoders)], input);
  }
  
  export interface Email {
    kind: "Email";
    arg1: string;
  }
  
  export function decodeEmail(varDecoders, input) {
  return codecs.decodeCustomTypeVariant("Email", ["Arg1"], [codecs.decodeString.bind(null)], input);
  }
  
  export interface FirstName {
    kind: "FirstName";
    arg1: string;
  }
  
  export function decodeFirstName(varDecoders, input) {
  return codecs.decodeCustomTypeVariant("FirstName", ["Arg1"], [codecs.decodeString.bind(null)], input);
  }
  
  
  export type FooBarBazRecord = {
    foo: string;
    bar: boolean;
    baz: number;
  }
  
  export function decodeFooBarBazRecord(varDecoders, input) {
  return codecs.decodeRecord(new Map([["foo", codecs.decodeString.bind(null)], ["bar", codecs.decodeBoolean.bind(null)], ["baz", codecs.decodeInt.bind(null)]]), input);
  }
  
  export function encodeFooBarBazRecord(varEncoders, value) {
  return codecs.encodeRecord(new Map([["foo", codecs.encodeString.bind(null)], ["bar", codecs.encodeBoolean.bind(null)], ["baz", codecs.encodeInt.bind(null)]]), value);
  }
  
  export interface FullName {
    kind: "FullName";
    arg1: Morphir_Reference_Model_Types.FirstName;
    arg2: Morphir_Reference_Model_Types.LastName;
  }
  
  export function decodeFullName(varDecoders, input) {
  return codecs.decodeCustomTypeVariant("FullName", ["Arg1", "Arg2"], [Morphir_Reference_Model_Types.decodeFirstName.bind(null, varDecoders), Morphir_Reference_Model_Types.decodeLastName.bind(null, varDecoders)], input);
  }
  
  export interface LastName {
    kind: "LastName";
    arg1: string;
  }
  
  export function decodeLastName(varDecoders, input) {
  return codecs.decodeCustomTypeVariant("LastName", ["Arg1"], [codecs.decodeString.bind(null)], input);
  }
  
  /* Alias referring to another type using a reference.
  */
  export type Quantity = number
  
  export function decodeQuantity(varDecoders, input) {
  return codecs.decodeInt(input);
  }
  
  export function encodeQuantity(varEncoders, value) {
  return codecs.encodeInt(value);
  }
  
}

