// Generated by morphir-elm

import * as codecs from "./../../../morphir/internal/Codecs"

export namespace Morphir_Reference_Model_Values {
  
  export type FruitAction = {
    fruitType: string;
    amount: number;
  }
  
  export function decodeFruitAction(varDecoders, input) {
  return codecs.decodeRecord(new Map([["fruitType", codecs.decodeString.bind(null)], ["amount", codecs.decodeFloat.bind(null)]]), input);
  }
  
  export function encodeFruitAction(varEncoders, value) {
  return codecs.encodeRecord(new Map([["fruitType", codecs.encodeString.bind(null)], ["amount", codecs.encodeFloat.bind(null)]]), value);
  }
  
}

