// Generated by morphir-elm

import * as codecs from "./../../../morphir/internal/Codecs";

export namespace Morphir_Reference_Model_Values {
  export type FruitAction = {
    fruitType: string;
    amount: number;
  };

  export function decodeFruitAction(input: any): FruitAction {
    return codecs.decodeRecord(
      codecs.buildCodecMap([
        ["fruitType", codecs.decodeString],
        ["amount", codecs.decodeFloat],
      ]),
      input
    );
  }

  export function encodeFruitAction(value: FruitAction): any {
    return codecs.encodeRecord(
      codecs.buildCodecMap([
        ["fruitType", codecs.encodeString],
        ["amount", codecs.encodeFloat],
      ]),
      value
    );
  }
}
