// Generated by morphir-elm



export namespace Morphir_Reference_Model_ValueEditors {
  
  export type LargeEnum = Option1 | Option10 | Option11 | Option12 | Option13 | Option14 | Option15 | Option16 | Option17 | Option18 | Option19 | Option2 | Option20 | Option3 | Option4 | Option5 | Option6 | Option7 | Option8 | Option9
  
  export interface Option1 {
    kind: "Option1";
  }
  
  export interface Option10 {
    kind: "Option10";
  }
  
  export interface Option11 {
    kind: "Option11";
  }
  
  export interface Option12 {
    kind: "Option12";
  }
  
  export interface Option13 {
    kind: "Option13";
  }
  
  export interface Option14 {
    kind: "Option14";
  }
  
  export interface Option15 {
    kind: "Option15";
  }
  
  export interface Option16 {
    kind: "Option16";
  }
  
  export interface Option17 {
    kind: "Option17";
  }
  
  export interface Option18 {
    kind: "Option18";
  }
  
  export interface Option19 {
    kind: "Option19";
  }
  
  export interface Option2 {
    kind: "Option2";
  }
  
  export interface Option20 {
    kind: "Option20";
  }
  
  export interface Option3 {
    kind: "Option3";
  }
  
  export interface Option4 {
    kind: "Option4";
  }
  
  export interface Option5 {
    kind: "Option5";
  }
  
  export interface Option6 {
    kind: "Option6";
  }
  
  export interface Option7 {
    kind: "Option7";
  }
  
  export interface Option8 {
    kind: "Option8";
  }
  
  export interface Option9 {
    kind: "Option9";
  }
  
  
  export type Price = number
  
  
  export type SmallEnum = OptionOne | OptionThree | OptionTwo
  
  export interface OptionOne {
    kind: "OptionOne";
  }
  
  export interface OptionThree {
    kind: "OptionThree";
  }
  
  export interface OptionTwo {
    kind: "OptionTwo";
  }
  
}

