// Generated by morphir-elm

import * as codecs from "./../../../../morphir/internal/Codecs"

export namespace Morphir_Reference_Model_Insight_UseCase1 {
  
  export type Direction = Down | Up
  
  export function decodeDirection(varDecoders, input) {
  let decoderMap = new Map();
  decoderMap.set("Down", decodeDown.bind(varDecoders));
  decoderMap.set("Up", decodeUp.bind(varDecoders));
  codecs.decodeCustomType(decoderMap, input);
  }
  
  
  
  export interface Down {
    kind: "Down";
  }
  
  export function decodeDown(varDecoders, input) {
  return codecs.decodeCustomTypeVariant("Down", [], [], input);
  }
  
  export interface Up {
    kind: "Up";
  }
  
  export function decodeUp(varDecoders, input) {
  return codecs.decodeCustomTypeVariant("Up", [], [], input);
  }
  
  
  export type TrackingAdvantage = {
    direction: Morphir_Reference_Model_Insight_UseCase1.Direction;
    code: string;
    velocity: number;
  }
  
  export function decodeTrackingAdvantage(varDecoders, input) {
  return codecs.decodeRecord(new Map([["direction", Morphir_Reference_Model_Insight_UseCase1.decodeDirection.bind(null, varDecoders)], ["code", codecs.decodeString.bind(null)], ["velocity", codecs.decodeFloat.bind(null)]]), input);
  }
  
  export function encodeTrackingAdvantage(varEncoders, value) {
  return codecs.encodeRecord(new Map([["direction", codecs.encodeUnit.bind(null)], ["code", codecs.encodeString.bind(null)], ["velocity", codecs.encodeFloat.bind(null)]]), value);
  }
  
}

