// Generated by morphir-elm

import * as codecs from "./../../../../morphir/internal/Codecs"

export namespace Morphir_Reference_Model_Presentations_UKFintechMeetup {
  
  export type Response = Rejected | Reserved
  
  export function decodeResponse(varDecoders, input) {
  let decoderMap = new Map();
  decoderMap.set("Rejected", decodeRejected.bind(varDecoders));
  decoderMap.set("Reserved", decodeReserved.bind(varDecoders));
  codecs.decodeCustomType(decoderMap, input);
  }
  
  
  
  export interface Rejected {
    kind: "Rejected";
  }
  
  export function decodeRejected(varDecoders, input) {
  return codecs.decodeCustomTypeVariant("Rejected", [], [], input);
  }
  
  export interface Reserved {
    kind: "Reserved";
    arg1: number;
  }
  
  export function decodeReserved(varDecoders, input) {
  return codecs.decodeCustomTypeVariant("Reserved", ["Arg1"], [codecs.decodeInt.bind(null)], input);
  }
  
}

