// Generated by morphir-elm

import { Morphir_Reference_Model_BooksAndRecords } from "./morphir/reference/model/BooksAndRecords";
import { Morphir_Reference_Model_Formulas } from "./morphir/reference/model/Formulas";
import { Morphir_Reference_Model_Insight_UseCase1 } from "./morphir/reference/model/insight/UseCase1";
import { Morphir_Reference_Model_Insight_UseCase2 } from "./morphir/reference/model/insight/UseCase2";
import { Morphir_Reference_Model_Issues_Common } from "./morphir/reference/model/issues/Common";
import { Morphir_Reference_Model_Issues_DecisionTables } from "./morphir/reference/model/issues/DecisionTables";
import { Morphir_Reference_Model_Issues_Issue210 } from "./morphir/reference/model/issues/Issue210";
import { Morphir_Reference_Model_Issues_Issue227 } from "./morphir/reference/model/issues/Issue227";
import { Morphir_Reference_Model_Issues_Issue273 } from "./morphir/reference/model/issues/Issue273";
import { Morphir_Reference_Model_Issues_Issue330 } from "./morphir/reference/model/issues/Issue330";
import { Morphir_Reference_Model_Issues_Issue331 } from "./morphir/reference/model/issues/Issue331";
import { Morphir_Reference_Model_Issues_Issue333 } from "./morphir/reference/model/issues/Issue333";
import { Morphir_Reference_Model_Issues_Issue349 } from "./morphir/reference/model/issues/Issue349";
import { Morphir_Reference_Model_Issues_Issue350 } from "./morphir/reference/model/issues/Issue350";
import { Morphir_Reference_Model_Issues_Issue364 } from "./morphir/reference/model/issues/Issue364";
import { Morphir_Reference_Model_Issues_Issue401 } from "./morphir/reference/model/issues/Issue401";
import { Morphir_Reference_Model_Issues_Issue407 } from "./morphir/reference/model/issues/Issue407";
import { Morphir_Reference_Model_Issues_Issue409 } from "./morphir/reference/model/issues/Issue409";
import { Morphir_Reference_Model_Issues_Issue410 } from "./morphir/reference/model/issues/Issue410";
import { Morphir_Reference_Model_Issues_Issue432 } from "./morphir/reference/model/issues/Issue432";
import { Morphir_Reference_Model_Issues_Issue448 } from "./morphir/reference/model/issues/Issue448";
import { Morphir_Reference_Model_Issues_Issue450 } from "./morphir/reference/model/issues/Issue450";
import { Morphir_Reference_Model_Issues_Issue493 } from "./morphir/reference/model/issues/Issue493";
import { Morphir_Reference_Model_Issues_PatternModel_BasicEnum } from "./morphir/reference/model/issues/patternmodel/BasicEnum";
import { Morphir_Reference_Model_Issues_PatternModel_OtherBasicEnum } from "./morphir/reference/model/issues/patternmodel/OtherBasicEnum";
import { Morphir_Reference_Model_Presentations_UKFintechMeetup } from "./morphir/reference/model/presentations/UKFintechMeetup";
import { Morphir_Reference_Model_SDK_Result } from "./morphir/reference/model/sdk/Result";
import { Morphir_Reference_Model_SDK_String } from "./morphir/reference/model/sdk/String";
import { Morphir_Reference_Model_SDK_Tuple } from "./morphir/reference/model/sdk/Tuple";
import { Morphir_Reference_Model_Types } from "./morphir/reference/model/Types";
import { Morphir_Reference_Model_ValueEditors } from "./morphir/reference/model/ValueEditors";
import { Morphir_Reference_Model_Values } from "./morphir/reference/model/Values";

export namespace Morphir {
  export namespace Reference {
    export namespace Model {
      export import BooksAndRecords = Morphir_Reference_Model_BooksAndRecords;

      export import Formulas = Morphir_Reference_Model_Formulas;

      export namespace Insight {
        export import UseCase1 = Morphir_Reference_Model_Insight_UseCase1;

        export import UseCase2 = Morphir_Reference_Model_Insight_UseCase2;
      }

      export namespace Issues {
        import Common = Morphir_Reference_Model_Issues_Common;

        export import DecisionTables = Morphir_Reference_Model_Issues_DecisionTables;

        export import Issue210 = Morphir_Reference_Model_Issues_Issue210;

        export import Issue227 = Morphir_Reference_Model_Issues_Issue227;

        export import Issue273 = Morphir_Reference_Model_Issues_Issue273;

        export import Issue330 = Morphir_Reference_Model_Issues_Issue330;

        export import Issue331 = Morphir_Reference_Model_Issues_Issue331;

        export import Issue333 = Morphir_Reference_Model_Issues_Issue333;

        export import Issue349 = Morphir_Reference_Model_Issues_Issue349;

        export import Issue350 = Morphir_Reference_Model_Issues_Issue350;

        export import Issue364 = Morphir_Reference_Model_Issues_Issue364;

        export import Issue401 = Morphir_Reference_Model_Issues_Issue401;

        export import Issue407 = Morphir_Reference_Model_Issues_Issue407;

        export import Issue409 = Morphir_Reference_Model_Issues_Issue409;

        export import Issue410 = Morphir_Reference_Model_Issues_Issue410;

        export import Issue432 = Morphir_Reference_Model_Issues_Issue432;

        export import Issue448 = Morphir_Reference_Model_Issues_Issue448;

        export import Issue450 = Morphir_Reference_Model_Issues_Issue450;

        export import Issue493 = Morphir_Reference_Model_Issues_Issue493;

        export namespace PatternModel {
          export import BasicEnum = Morphir_Reference_Model_Issues_PatternModel_BasicEnum;

          export import OtherBasicEnum = Morphir_Reference_Model_Issues_PatternModel_OtherBasicEnum;
        }
      }

      export namespace Presentations {
        export import UKFintechMeetup = Morphir_Reference_Model_Presentations_UKFintechMeetup;
      }

      export namespace SDK {
        export import Result = Morphir_Reference_Model_SDK_Result;

        export import String = Morphir_Reference_Model_SDK_String;

        export import Tuple = Morphir_Reference_Model_SDK_Tuple;
      }

      export import Types = Morphir_Reference_Model_Types;

      export import ValueEditors = Morphir_Reference_Model_ValueEditors;

      export import Values = Morphir_Reference_Model_Values;
    }
  }
}
