// Generated by morphir-elm

import { Codethink_PrizeDraws_AutoGen } from "./codethink/prizedraws/AutoGen"

export namespace Codethink {
  export namespace PrizeDraws {
    export import AutoGen = Codethink_PrizeDraws_AutoGen
    
  }
  
}

